-- +goose Up
-- OpenID Provider state (ADR-0001). These tables back the zitadel/oidc
-- op.Storage adapter. They are deliberately separate from the hand-rolled
-- oauth_* tables: the OP stores token *IDs* and reference records, not the
-- normalized rows the old engine used, and the old tables are retired in
-- Phase 4. Until then both sets coexist.
--
-- At-rest rule is unchanged: bearer values are never stored. Access tokens are
-- keyed by sha256(tokenID) and refresh tokens by sha256(value); the plaintext
-- appears only inside the encrypted bearer token or on the wire.

CREATE TABLE oidc_auth_requests (
    id                    text PRIMARY KEY,
    client_id             text        NOT NULL,
    redirect_uri          text        NOT NULL,
    response_type         text        NOT NULL,
    response_mode         text        NOT NULL DEFAULT '',
    scopes                text[]      NOT NULL DEFAULT '{}',
    state                 text        NOT NULL DEFAULT '',
    nonce                 text        NOT NULL DEFAULT '',
    code_challenge        text        NOT NULL DEFAULT '',
    code_challenge_method text        NOT NULL DEFAULT '',
    subject               text        NOT NULL DEFAULT '',
    done                  boolean     NOT NULL DEFAULT false,
    auth_time             timestamptz,
    created_at            timestamptz NOT NULL,
    expires_at            timestamptz NOT NULL
);

CREATE INDEX oidc_auth_requests_expires_idx ON oidc_auth_requests (expires_at);

-- code_hash -> auth request. The code is generated by the library and is
-- single-use; the row is deleted together with its request.
CREATE TABLE oidc_codes (
    code_hash  text PRIMARY KEY,
    request_id text        NOT NULL,
    expires_at timestamptz NOT NULL
);

CREATE INDEX oidc_codes_expires_idx ON oidc_codes (expires_at);

CREATE TABLE oidc_access_tokens (
    id_hash    text PRIMARY KEY,
    client_id  text        NOT NULL,
    subject    text        NOT NULL,
    scopes     text[]      NOT NULL DEFAULT '{}',
    expires_at timestamptz NOT NULL
);

CREATE INDEX oidc_access_tokens_expires_idx ON oidc_access_tokens (expires_at);
CREATE INDEX oidc_access_tokens_subject_idx ON oidc_access_tokens (subject, client_id);

CREATE TABLE oidc_refresh_tokens (
    token_hash text PRIMARY KEY,
    id_hash    text        NOT NULL,
    client_id  text        NOT NULL,
    subject    text        NOT NULL,
    scopes     text[]      NOT NULL DEFAULT '{}',
    amr        text[]      NOT NULL DEFAULT '{}',
    audience   text[]      NOT NULL DEFAULT '{}',
    auth_time  timestamptz,
    expires_at timestamptz NOT NULL
);

CREATE INDEX oidc_refresh_tokens_expires_idx ON oidc_refresh_tokens (expires_at);

CREATE TABLE oidc_devices (
    device_code_hash text PRIMARY KEY,
    user_code        text        NOT NULL,
    client_id        text        NOT NULL,
    scopes           text[]      NOT NULL DEFAULT '{}',
    done             boolean     NOT NULL DEFAULT false,
    denied           boolean     NOT NULL DEFAULT false,
    subject          text        NOT NULL DEFAULT '',
    auth_time        timestamptz,
    expires_at       timestamptz NOT NULL
);

-- User codes are case- and separator-insensitive; the unique index is what
-- makes "this user code is already taken" detectable as a constraint error.
CREATE UNIQUE INDEX oidc_devices_user_code_idx
    ON oidc_devices (upper(replace(user_code, '-', '')));

-- +goose Down
DROP TABLE IF EXISTS oidc_devices;
DROP TABLE IF EXISTS oidc_refresh_tokens;
DROP TABLE IF EXISTS oidc_access_tokens;
DROP TABLE IF EXISTS oidc_codes;
DROP TABLE IF EXISTS oidc_auth_requests;
