-- +goose Up
--
-- Pseudonymisation of audit subjects.
--
-- The audit log names an account on nearly every row. That makes it a personal
-- data store in its own right, and it means an erasure that leaves the log alone
-- leaves the person's trail in place. This table is the destructible half of the
-- fix: audit rows carry a keyed pseudonym instead of the raw `usr_`, and deleting
-- one row here makes that account's whole history unlinkable — without touching a
-- single audit row, so the chain built in 0013 stays intact.
--
--   idx       = HMAC(audit key, "…subject-index/1" ‖ subject)   -- the lookup
--   key       = 32 random bytes                                  -- per subject
--   pseudonym = HMAC(key, "…pseudonym/1" ‖ subject)
--
-- The subject itself is deliberately NOT stored: `idx` is a keyed hash, so a
-- database dump does not contain the account ids in this table either. The audit
-- key lives in the environment, so a dump alone cannot recompute `idx` for a
-- candidate subject and therefore cannot resolve a pseudonym back to an account.
--
-- What this does and does not buy, stated plainly:
--
--   * after an erasure  -> the row is gone, so the pseudonym cannot be recomputed
--     from the subject by anyone, including this service. That is the point.
--   * before an erasure -> a dump of the whole database can still re-link a live
--     account's audit rows, because it contains both these keys and the account
--     ids. It also contains the account's identities and email, so that dump was
--     already total. Pseudonymisation is not a substitute for not being breached;
--     what it delivers is erasure.
--
-- Rows written before this migration keep whatever they already had. They are not
-- rewritten, because rewriting them would either invalidate the hashes written
-- over the old value (breaking 0013's chain) or require an in-Go data migration at
-- startup. See docs/architecture.md §4.17.

-- IF NOT EXISTS for the same reason as 0013: 0014's Down is a no-op, goose
-- still deletes the version row for it, and the next Open() re-runs this Up.
CREATE TABLE IF NOT EXISTS audit_subject_keys (
    idx text  PRIMARY KEY,
    key bytea NOT NULL
);

-- +goose Down
--
-- This step is NOT reversible, and deliberately executes nothing.
--
-- It used to drop the whole audit_subject_keys table, the ONLY copy of every
-- per-subject pseudonym key. Dropping it splits every live subject's pseudonym
-- history: the next audit append for that subject finds no key, mints a fresh
-- random one (auditpseudo.go, subjectKey), and every row written afterwards
-- carries a different pseudonym than the same account's older rows. The admin
-- read path (?subject=usr_…) then answers with only the post-wipe rows — a
-- silently truncated history, with nothing in Verify to notice because every
-- remaining row is still chain-valid. And the re-Up re-creates the table empty
-- and would collide on the table name if this section were a partial no-op
-- instead of an empty one.
--
-- A key table cannot be "rolled back" without destroying the erasure property
-- it exists for, so rollback is restore-from-backup (ADR-0008 §5). The same
-- MigrateDown refusal helps here only indirectly: the pseudonym keys are a
-- 0014 object, and 0014 is refused on the same terms as 0013 because it is
-- stacked on the chain it pseudonymises. Keeping the section empty is the
-- control for the operator driving the goose CLI directly.
--
-- Do not add DDL to this section: `TestAuditIntegrityMigrationsCannotBeRolledBack`
-- fails on any executed statement here.
